version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing jq..."
      - apt-get update && apt-get install -y jq
      - echo "Fetching AWS credentials..."
      - CREDS=$(curl -s "http://169.254.170.2${AWS_CONTAINER_CREDENTIALS_RELATIVE_URI}")
      - export AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r '.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r '.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo $CREDS | jq -r '.Token')
      - mkdir -p ~/.aws
      - |
        cat > ~/.aws/credentials <<EOL
[default]
aws_access_key_id=$AWS_ACCESS_KEY_ID
aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
aws_session_token=$AWS_SESSION_TOKEN
EOL
      - echo "Credentials stored in ~/.aws/credentials"
  build:
    commands:
      - echo "Now your app can use these credentials securely!"
