AWSTemplateFormatVersion: '2010-09-09'
Description: Create an IAM user with ReadOnlyAccess and access keys

Resources:

  DemoReadOnlyUser:
    Type: AWS::IAM::User
    Properties:
      UserName: DemoReadOnlyUser

  ReadOnlyGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: ReadOnlyGroup
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess

  AddUserToGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref ReadOnlyGroup
      Users:
        - !Ref DemoReadOnlyUser

  DemoUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref DemoReadOnlyUser
      Status: Active

Outputs:

  DemoUserName:
    Description: The name of the IAM user
    Value: !Ref DemoReadOnlyUser

  AccessKeyId:
    Description: Access Key ID for the IAM user
    Value: !Ref DemoUserAccessKey
    Export:
      Name: DemoUserAccessKeyId

  SecretAccessKey:
    Description: Secret Access Key for the IAM user
    Value: !GetAtt DemoUserAccessKey.SecretAccessKey
    Export:
      Name: DemoUserSecretAccessKey
